os: windows
language: csharp
solution: wfSpaceInvaders/wfSpaceInvaders.sln
mono: latest
dotnet: latest
language: bash
script:
  - choco install dotnetcore-sdk
  - dotnet restore wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
  - msbuild wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
