language: csharp
solution: solution-name.sln
mono:
  - latest
solution: wfSpaceInvaders/wfSpaceInvaders.sln

script:
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj 




