language: csharp
mono: latest
dotnet: 3.1.402
solution: wfSpaceInvaders/wfSpaceInvaders.sln

install:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  
before_script:
  - nuget restore wfSpaceInvaders/wfSpaceInvaders.sln

script:
  - dotnet restore
  - dotnet test 

notifications:
email:
    if: branch = master
    recipients:
      - 101227897@students.swinburne.edu.my
      - 101227910@students.swinburne.edu.my
      - 101229822@students.swinburne.edu.my
    on_success: never
    on_failure: always



