language: csharp
solution: wfSpaceInvaders/wfSpaceInvaders.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 3.8.0
  - 3.2.8
  - 2.10.8
dotnet: 3.1.2
os: windows
script:
  - dotnet restore wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
  - msbuild wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
