language: csharp
solution: wfSpaceInvaders/wfSpaceInvaders.sln
mono: latest
dotnet: 3.1.2
script:
  - dotnet restore
  - msbuild
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
