os: windows
language: csharp
solution: wfSpaceInvaders/wfSpaceInvaders.sln
mono: none
install:
  - choco install dotnetcore-sdk
  - dotnet restore wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
script:
  - msbuild wfSpaceInvaders/wfSpaceInvadersTest/wfSpaceInvadersTest.csproj
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
