language: csharp
solution: wfSpaceInvaders/wfSpaceInvaders.sln
mono: latest
dotnet: 3.1.2
before_install:
  - cd wfSpaceInvaders
script:
  - dotnet restore
  - msbuild
  - dotnet test ../wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
