language: csharp
mono: latest
dotnet: 3.1.2
before_install:
  - cd src
script:
  - dotnet restore
  - msbuild
  - dotnet test wfSpaceInvaders/wfSpaceInvadersTest/bin/Debug/netcoreapp3.1/wfSpaceInvadersTest.dll
